server:
 port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234